/**
 * pos = part of speech
 */

// const vocabulary = {
//     '自然地理': {
//         label: '自然地理',
//         words: [
//             {id: 1, word: 'atmosphere', pos: 'n.', meaning: '大气层；气氛', example: '', extra: 'working/relaxing/learning atmosphere 工作/放松/学习氛围'},
//             {id: 2, word: 'hydrosphere', pos: 'n.', meaning: '大气中的水汽；水圈', example: '', extra: ''},
//             {id: 3, word: 'lithosphere', pos: 'n.', meaning: '岩石圈', example: '', extra: ''},
//             {id: 4, word: 'oxygen', pos: 'n.', meaning: '氧气', example: '', extra: 'gases 气体'},
//             {id: 5, word: 'oxide', pos: 'n.', meaning: '氧化物', example: '', extra: ''},
//             {id: 6, word: 'carbon dioxide', pos: 'n.', meaning: '二氧化碳', example: '', extra: ''},
//             {id: 7, word: 'hydrogen', pos: 'n.', meaning: '氢气', example: '', extra: 'hydro水，gen生成；generation gap 代沟'},
//             {id: 8, word: 'core', pos: 'n.', meaning: '中心，核心，地核', example: '', extra: ''},
//             {id: 9, word: 'crust', pos: 'n.', meaning: '地壳；面包皮', example: '', extra: ''},
//             {id: 10, word: 'mantle', pos: 'n.', meaning: '地幔；斗篷披风； v. 覆盖', example: '', extra: ''},
//             {id: 11, word: 'longitude', pos: 'n.', meaning: '经度', example: 'a line of longitude 经线', extra: ''},
//             {id: 12, word: 'latitude', pos: 'n.', meaning: '纬度', example: 'hight latitude', extra: ''},
//             {id: 13, word: 'altitude', pos: 'n.', meaning: '海拔', example: '', extra: ''},
//             {id: 14, word: 'horizon', pos: 'n.', meaning: '地平线', example: 'broaden sb\'s horizon 扩展某人的视野', extra: ''},
//             {id: 15, word: 'disaster', pos: 'n.', meaning: '灾难', example: '', extra: 'adj. disastrous'},
//             {id: 16, word: 'mishap', pos: 'adj.', meaning: '小灾难的', example: '', extra: ''},
//             {id: 17, word: 'catastrophic', pos: 'adj.', meaning: '灾难性的', example: '', extra: ''},
//             {id: 18, word: 'calamity', pos: 'n.', meaning: '灾难不幸', example: '', extra: 'cause a calamity'},
//             {id: 19, word: 'endanger', pos: 'v.', meaning: '灾难不幸', example: '', extra: 'enforce 加强； enlarge 变大'},
//             {id: 20, word: 'jeopardise', pos: 'v.', meaning: '危害、危及', example: '', extra: 'jeopardise sb\'s life'},
//             {id: 21, word: 'destructive', pos: 'adj.', meaning: '有害的', example: '', extra: 'destruct v. 毁坏；mass destructive weapon 大规模杀伤性武器'},
//             {id: 22, word: 'El Nino', pos: 'n.', meaning: '厄尔尼诺，一种气候现象', example: '', extra: '来源于西语圣经，是圣婴的意思'},
//             {id: 23, word: 'greenhouse', pos: 'n.', meaning: '温室', example: '', extra: 'the greenhouse effect 温室效应'},
//             {id: 24, word: 'phenomenon', pos: 'n.', meaning: '现象', example: '', extra: ''},
//             {id: 25, word: 'pebble', pos: 'n.', meaning: '鹅卵石', example: '', extra: ''},
//             {id: 26, word: 'magnet', pos: 'n.', meaning: '磁铁', example: '', extra: 'magnetic adj. 磁的；magnetic field 磁场；magnetic therapy 磁疗'},
//             {id: 27, word: 'ore', pos: 'n.', meaning: '矿石；矿', example: '', extra: ''},
//             {id: 28, word: 'mineral', pos: 'n.', meaning: '矿物质；矿产', example: 'mineral water 矿泉水', extra: 'under mine 暗中破坏、削弱'},
//             {id: 29, word: 'marble', pos: 'n.', meaning: '大理石；弹球', example: '', extra: ''},
//             {id: 30, word: 'quartz', pos: 'n.', meaning: '石英', example: 'quartz clock 石英钟', extra: 'quarter 四分子一'},
//             {id: 31, word: 'granite', pos: 'n.', meaning: '花岗岩', example: 'bite on granite 徒劳', extra: ''},
//             {id: 32, word: 'breeze', pos: 'n.', meaning: '微风', example: '', extra: ''},
//             {id: 33, word: 'gust', pos: 'n.', meaning: '狂风', example: '', extra: ''},
//             {id: 34, word: 'gale', pos: 'n.', meaning: '大风', example: 'a servere gale 一阵大风', extra: ''},
//             {id: 35, word: 'hurricane', pos: 'n.', meaning: '飓风；风暴', example: '', extra: 'cyclone 气旋'},
//             {id: 36, word: 'tornado', pos: 'n.', meaning: '龙卷风', example: '', extra: 'twister旋风'},
//             {id: 37, word: 'typhoon', pos: 'n.', meaning: '台风', example: '', extra: 'tycoon 大亨'},
//             {id: 38, word: 'monsoon', pos: 'n.', meaning: '季风', example: 'monsoon season 雨季', extra: ''},
//             {id: 39, word: 'volcano', pos: 'n.', meaning: '火山', example: 'extinct volcano 死火山；sit no volcano 处境危险', extra: ''},
//             {id: 40, word: 'erupt', pos: 'v.', meaning: '爆发', example: '', extra: 'eruption n. 喷发；explode 爆炸'},
//             {id: 41, word: 'magma', pos: 'n.', meaning: '岩浆', example: '', extra: 'lava n. 岩浆、火山石'},
//             {id: 42, word: 'thermodynamic', pos: 'adj.', meaning: '热力的', example: '', extra: 'thermodynamics 热力学的；thermometer 体温计，温度计'},
//             {id: 43, word: 'smog', pos: 'n.', meaning: '烟雾；雾霾', example: '', extra: '合成词'},
//             {id: 44, word: 'fume', pos: 'n.', meaning: '有害气体，v. 冒烟', example: '', extra: ''},
//             {id: 45, word: 'mist', pos: 'n.', meaning: '雾霾；水汽', example: 'mist of tears 泪眼模糊', extra: ''},
//             {id: 46, word: 'tsunami', pos: 'n.', meaning: '海啸', example: '', extra: 'wasabi 芥末'},
//             {id: 47, word: 'flooding', pos: 'n.', meaning: '洪水泛滥', example: '', extra: ''},
//             {id: 48, word: 'torrent', pos: 'n.', meaning: '激流', example: '', extra: 'current'},
//             {id: 49, word: 'drought', pos: 'n.', meaning: '干旱，旱灾', example: '', extra: 'dry/arid 干燥的'},
//             {id: 50, word: 'earthquake', pos: 'n.', meaning: '地震', example: '', extra: 'dry/arid 干燥的'},
//             {id: 51, word: 'seismic', pos: 'adj.', meaning: '地震的，地震引起的', example: 'a seismic wave 地震波', extra: ''},
//             {id: 52, word: 'avalanche', pos: 'n.', meaning: '雪崩', example: '', extra: ''},
//             {id: 53, word: 'terrain', pos: 'n.', meaning: '地形', example: 'a terrain feature 地形特征', extra: ''},
//             {id: 54, word: 'landscape', pos: 'n.', meaning: '风景；对...进行美化', example: '', extra: ''},
//             {id: 55, word: 'continent', pos: 'n.', meaning: '大陆、洲', example: '', extra: 'continental breakfast 欧早餐'},
//             {id: 56, word: 'cave', pos: 'n.', meaning: '洞穴', example: '', extra: ''},
//             {id: 57, word: 'cliff', pos: 'n.', meaning: '峭壁，悬崖', example: '', extra: ''},
//             {id: 58, word: 'glacier', pos: 'n.', meaning: '冰川', example: '', extra: ''},
//             {id: 59, word: 'swamp', pos: 'n.', meaning: '沼泽，湿地', example: '', extra: ''},
//             {id: 60, word: 'delta', pos: 'n.', meaning: '三角洲', example: '', extra: 'Alpha Omega'},
//             {id: 61, word: 'plain', pos: 'n./adj.', meaning: '平原；简单朴素的', example: '', extra: 'just plain cloth'},
//             {id: 62, word: 'plateau', pos: 'n.', meaning: '高原', example: 'plateau climate高原气候', extra: '图表中维持高位 reached plateau；platform 站台、平台'},
//             {id: 63, word: 'oasis', pos: 'n.', meaning: '绿洲', example: '', extra: ''},
//             {id: 64, word: 'globe', pos: 'n.', meaning: '球体；地球仪', example: '', extra: ''},
//             {id: 65, word: 'hemisphere', pos: 'n.', meaning: '半球，脑半球，球体的一半', example: 'Southern hemisphere 南半球', extra: ''},
//             {id: 66, word: 'equator', pos: 'n.', meaning: '赤道', example: '', extra: ''},
//             {id: 67, word: 'equal', pos: 'adj.', meaning: '相当的', example: 'all men are created equal 人生来平等', extra: ''},
//             {id: 68, word: 'arctic', pos: 'n./adj.', meaning: '北极，北极的', example: '', extra: ''},
//             {id: 69, word: 'Antarctic', pos: 'adj.', meaning: '南极的', example: '', extra: ''},
//             {id: 70, word: 'pole', pos: 'n.', meaning: '两极的一极', example: '', extra: ''},
//             {id: 71, word: 'polar', pos: 'adj.', meaning: '极地，对立的', example: '', extra: 'polarize v. 两极分化；xxx also polarized our socity'},
//             {id: 72, word: 'axis', pos: 'n.', meaning: '轴线', example: '', extra: 'axe 斧头'},
//             {id: 73, word: 'deteriorate', pos: 'v.', meaning: '恶化；加重', example: '', extra: ''},
//             {id: 74, word: 'aggravate', pos: 'v.', meaning: '恶化；加重', example: '', extra: 'gravity 重力、引力'},
//             {id: 75, word: 'degrade', pos: 'v.', meaning: '降级、降解、贬低', example: '', extra: 'degradeble 可降解的'},
//             {id: 76, word: 'upgrade', pos: 'v.', meaning: '升级、提高', example: 'upgrade sth. to sth. 升级为', extra: 'up to date 现代的'},
//             {id: 77, word: 'erode', pos: 'v.', meaning: '侵蚀、腐蚀', example: '', extra: 'erosion n. 侵蚀'},
//             {id: 78, word: 'Mediterranean', pos: 'adj.', meaning: '地中海的', example: '', extra: ''},
//             {id: 79, word: 'Atlantic', pos: 'n./adj.', meaning: '大西洋，大西洋的', example: '', extra: ''},
//             {id: 80, word: 'ocean', pos: 'n.', meaning: '海洋', example: 'ocean\'s of 大量的', extra: ''},
//         ],
//     },
//     '植物研究': {
//         label: '植物研究',
//         words: [],
//     },
//     '动物保护': {
//         label: '动物保护',
//         words: [],
//     },
//     '建筑场所': {
//         label: '建筑场所',
//         words: [],
//     },
// }

const vocabulary = { '自然地理': { 'label': '自然地理', 'words': [[{ 'id': 1, 'word': 'ocean', 'pos': 'n.', 'meaning': '海洋；洋', 'example': 'These creatures live in the depth of the Pacific Ocean', 'extra': 'an ocean of/oceans of 大量' }, { 'id': 2, 'word': 'marine', 'pos': 'adj. n.', 'meaning': '海洋的；海生的；海事的；水兵', 'example': 'It is true that a lot of people like marine plants as their food', 'extra': 'a marine product 海产品；船用品' }, { 'id': 3, 'word': 'navigation', 'pos': 'n.', 'meaning': '航海；航行', 'example': 'Navigation is a game for brave people', 'extra': 'navigator n. 航海家；领航员' }, { 'id': 4, 'word': '' }], [{ 'id': 5, 'word': 'gulf', 'pos': 'n.', 'meaning': '海湾' }, { 'id': 6, 'word': 'beach', 'pos': 'n.', 'meaning': '海滩；河滩' }, { 'id': 7, 'word': 'coast', 'pos': 'n.', 'meaning': '海岸；海滨' }, { 'id': 8, 'word': '' }], [{ 'id': 9, 'word': 'shore', 'pos': 'n.', 'meaning': '（海、湖等大水域的）岸；滨', 'example': 'His ship pulled in to the shore at midnight' }, { 'id': 10, 'word': 'tide', 'pos': 'n.', 'meaning': '趋势；潮流；潮汐', 'example': 'The gravitational attraction between the moon and the earth causes tides', 'extra': 'tidal adj. 潮汐的。at low tide 退潮时，低潮时。Time and tide wait for no man 岁月不等人' }, { 'id': 11, 'word': 'current', 'pos': 'n.', 'meaning': '水流；潮流；电流；气流', 'example': 'He was swept away by the current' }, { 'id': 12, 'word': '' }], [{ 'id': 13, 'word': 'brook', 'pos': 'n.', 'meaning': '小河；溪' }, { 'id': 14, 'word': 'stream', 'pos': 'n. v.', 'meaning': '小河；溪；流；流动；流出' }, { 'id': 15, 'word': 'source' }, { 'id': 16, 'word': 'shallow' }, { 'id': 17, 'word': '' }]] }, '植物研究': { 'label': '植物研究', 'words': [[{ 'id': 18, 'word': 'photosynthesis', 'pos': 'n.', 'meaning': '光合作用' }, { 'id': 19, 'word': 'respire', 'pos': 'v.', 'meaning': '呼吸' }, { 'id': 20, 'word': 'dioxide', 'pos': 'n.', 'meaning': '二氧化物' }, { 'id': 21, 'word': '' }]] }, '动物保护': { 'label': '动物保护', 'words': [[{ 'id': 22, 'word': 'biologist', 'pos': 'n.', 'meaning': '生物学家' }, { 'id': 23, 'word': 'zoologist', 'pos': 'n.', 'meaning': '动物学家' }, { 'id': 24, 'word': 'ecologist', 'pos': 'n.', 'meaning': '生态学家' }, { 'id': 25, 'word': 'botanist', 'pos': 'n.', 'meaning': '植物学家' }]] } }